/*
 * SOBIO
 * SOBIO Biometric Services
 *
 * OpenAPI spec version: 1
 * Contact: info@softwaredelcentro.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ar.com.sdc.sobio.model.v1;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * AuditData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-08-01T17:51:31.127-03:00")
public class AuditData {
  @JsonProperty("date")
  private DateTime date = null;

  @JsonProperty("result")
  private String result = null;

  @JsonProperty("subjectId")
  private String subjectId = null;

  @JsonProperty("token")
  private String token = null;

  @JsonProperty("txId")
  private String txId = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    ACTUALIZACION("ACTUALIZACION"),
    
    BORRADO("BORRADO"),
    
    BUSQUEDA_DUPLICADOS("BUSQUEDA_DUPLICADOS"),
    
    ENROLAMIENTO("ENROLAMIENTO"),
    
    ENROLAMIENTO_BATCH("ENROLAMIENTO_BATCH"),
    
    EXTRACCION_HUELLA("EXTRACCION_HUELLA"),
    
    EXTRACCION_ROSTRO("EXTRACCION_ROSTRO"),
    
    EXTRACCION_TEMPLATE("EXTRACCION_TEMPLATE"),
    
    EXTRACCION_VOZ("EXTRACCION_VOZ"),
    
    EXTRACT_DOCUMENT_INFO("EXTRACT_DOCUMENT_INFO"),
    
    IDENTIFICACION("IDENTIFICACION"),
    
    LOGGING_API_REQUEST_RESPONSE("LOGGING_API_REQUEST_RESPONSE"),
    
    OBTENER_INFORMACION_SUJETO("OBTENER_INFORMACION_SUJETO"),
    
    OBTENER_TEMPLATE("OBTENER_TEMPLATE"),
    
    UI_COMPONENT_ENROLL("UI_COMPONENT_ENROLL"),
    
    UI_COMPONENT_EXTRACT_DOCUMENT_INFO("UI_COMPONENT_EXTRACT_DOCUMENT_INFO"),
    
    UI_COMPONENT_VERIFY("UI_COMPONENT_VERIFY"),
    
    UI_EXTRACT_DOCUMENT_INFO("UI_EXTRACT_DOCUMENT_INFO"),
    
    VERIFICACION("VERIFICACION"),
    
    VERIFICAR_T2T("VERIFICAR_T2T");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("type")
  private TypeEnum type = null;

  public AuditData date(DateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(value = "")
  public DateTime getDate() {
    return date;
  }

  public void setDate(DateTime date) {
    this.date = date;
  }

  public AuditData result(String result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @ApiModelProperty(value = "")
  public String getResult() {
    return result;
  }

  public void setResult(String result) {
    this.result = result;
  }

  public AuditData subjectId(String subjectId) {
    this.subjectId = subjectId;
    return this;
  }

   /**
   * Get subjectId
   * @return subjectId
  **/
  @ApiModelProperty(value = "")
  public String getSubjectId() {
    return subjectId;
  }

  public void setSubjectId(String subjectId) {
    this.subjectId = subjectId;
  }

  public AuditData token(String token) {
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @ApiModelProperty(value = "")
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public AuditData txId(String txId) {
    this.txId = txId;
    return this;
  }

   /**
   * Get txId
   * @return txId
  **/
  @ApiModelProperty(value = "")
  public String getTxId() {
    return txId;
  }

  public void setTxId(String txId) {
    this.txId = txId;
  }

  public AuditData type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuditData auditData = (AuditData) o;
    return Objects.equals(this.date, auditData.date) &&
        Objects.equals(this.result, auditData.result) &&
        Objects.equals(this.subjectId, auditData.subjectId) &&
        Objects.equals(this.token, auditData.token) &&
        Objects.equals(this.txId, auditData.txId) &&
        Objects.equals(this.type, auditData.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, result, subjectId, token, txId, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuditData {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    subjectId: ").append(toIndentedString(subjectId)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

