/*
 * SOBIO
 * SOBIO Biometric Services
 *
 * OpenAPI spec version: 1
 * Contact: info@softwaredelcentro.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ar.com.sdc.sobio.model.v1;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * AuditByDateInput
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-08-01T15:33:45.277-03:00")
public class AuditByDateInput {
  @JsonProperty("dateFrom")
  private DateTime dateFrom = null;

  @JsonProperty("dateTo")
  private DateTime dateTo = null;

  @JsonProperty("maxResults")
  private Integer maxResults = null;

  public AuditByDateInput dateFrom(DateTime dateFrom) {
    this.dateFrom = dateFrom;
    return this;
  }

   /**
   * Get dateFrom
   * @return dateFrom
  **/
  @ApiModelProperty(required = true, value = "")
  public DateTime getDateFrom() {
    return dateFrom;
  }

  public void setDateFrom(DateTime dateFrom) {
    this.dateFrom = dateFrom;
  }

  public AuditByDateInput dateTo(DateTime dateTo) {
    this.dateTo = dateTo;
    return this;
  }

   /**
   * Get dateTo
   * @return dateTo
  **/
  @ApiModelProperty(required = true, value = "")
  public DateTime getDateTo() {
    return dateTo;
  }

  public void setDateTo(DateTime dateTo) {
    this.dateTo = dateTo;
  }

  public AuditByDateInput maxResults(Integer maxResults) {
    this.maxResults = maxResults;
    return this;
  }

   /**
   * Get maxResults
   * @return maxResults
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getMaxResults() {
    return maxResults;
  }

  public void setMaxResults(Integer maxResults) {
    this.maxResults = maxResults;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuditByDateInput auditByDateInput = (AuditByDateInput) o;
    return Objects.equals(this.dateFrom, auditByDateInput.dateFrom) &&
        Objects.equals(this.dateTo, auditByDateInput.dateTo) &&
        Objects.equals(this.maxResults, auditByDateInput.maxResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateFrom, dateTo, maxResults);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuditByDateInput {\n");
    
    sb.append("    dateFrom: ").append(toIndentedString(dateFrom)).append("\n");
    sb.append("    dateTo: ").append(toIndentedString(dateTo)).append("\n");
    sb.append("    maxResults: ").append(toIndentedString(maxResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

