/*
 * SOBIO
 * SOBIO Biometric Services
 *
 * OpenAPI spec version: 1
 * Contact: info@softwaredelcentro.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ar.com.sdc.sobio.model.v1;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ConvertFingerprintImageInput
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-09-28T07:51:40.431-03:00")
public class ConvertFingerprintImageInput {
  @JsonProperty("auditToken")
  private String auditToken = null;

  @JsonProperty("flipH")
  private Boolean flipH = null;

  @JsonProperty("flipV")
  private Boolean flipV = null;

  @JsonProperty("image")
  private String image = null;

  public ConvertFingerprintImageInput auditToken(String auditToken) {
    this.auditToken = auditToken;
    return this;
  }

   /**
   * Get auditToken
   * @return auditToken
  **/
  @ApiModelProperty(required = true, value = "")
  public String getAuditToken() {
    return auditToken;
  }

  public void setAuditToken(String auditToken) {
    this.auditToken = auditToken;
  }

  public ConvertFingerprintImageInput flipH(Boolean flipH) {
    this.flipH = flipH;
    return this;
  }

   /**
   * Get flipH
   * @return flipH
  **/
  @ApiModelProperty(value = "")
  public Boolean isFlipH() {
    return flipH;
  }

  public void setFlipH(Boolean flipH) {
    this.flipH = flipH;
  }

  public ConvertFingerprintImageInput flipV(Boolean flipV) {
    this.flipV = flipV;
    return this;
  }

   /**
   * Get flipV
   * @return flipV
  **/
  @ApiModelProperty(value = "")
  public Boolean isFlipV() {
    return flipV;
  }

  public void setFlipV(Boolean flipV) {
    this.flipV = flipV;
  }

  public ConvertFingerprintImageInput image(String image) {
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @ApiModelProperty(required = true, value = "")
  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConvertFingerprintImageInput convertFingerprintImageInput = (ConvertFingerprintImageInput) o;
    return Objects.equals(this.auditToken, convertFingerprintImageInput.auditToken) &&
        Objects.equals(this.flipH, convertFingerprintImageInput.flipH) &&
        Objects.equals(this.flipV, convertFingerprintImageInput.flipV) &&
        Objects.equals(this.image, convertFingerprintImageInput.image);
  }

  @Override
  public int hashCode() {
    return Objects.hash(auditToken, flipH, flipV, image);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConvertFingerprintImageInput {\n");
    
    sb.append("    auditToken: ").append(toIndentedString(auditToken)).append("\n");
    sb.append("    flipH: ").append(toIndentedString(flipH)).append("\n");
    sb.append("    flipV: ").append(toIndentedString(flipV)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

