/*
 * SOBIO
 * SOBIO Biometric Services
 *
 * OpenAPI spec version: 1
 * Contact: info@softwaredelcentro.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ar.com.sdc.sobio.model.v1;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * DetectedAction
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-26T12:55:02.459-03:00")
public class DetectedAction {
  @JsonProperty("frameNum")
  private Integer frameNum = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    LOOKING_LEFT("LOOKING_LEFT"),
    
    LOOKING_RIGHT("LOOKING_RIGHT"),
    
    LOOKING_UPWARDS("LOOKING_UPWARDS"),
    
    LOOKING_DOWNWARDS("LOOKING_DOWNWARDS"),
    
    LOOKING_FRONT("LOOKING_FRONT"),
    
    RIGHT_EYE_BLINK("RIGHT_EYE_BLINK"),
    
    LEFT_EYE_BLINK("LEFT_EYE_BLINK");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("type")
  private TypeEnum type = null;

  public DetectedAction frameNum(Integer frameNum) {
    this.frameNum = frameNum;
    return this;
  }

   /**
   * Get frameNum
   * @return frameNum
  **/
  @ApiModelProperty(value = "")
  public Integer getFrameNum() {
    return frameNum;
  }

  public void setFrameNum(Integer frameNum) {
    this.frameNum = frameNum;
  }

  public DetectedAction type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetectedAction detectedAction = (DetectedAction) o;
    return Objects.equals(this.frameNum, detectedAction.frameNum) &&
        Objects.equals(this.type, detectedAction.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(frameNum, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetectedAction {\n");
    
    sb.append("    frameNum: ").append(toIndentedString(frameNum)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

