/*
 * SOBIO
 * SOBIO Biometric Services
 *
 * OpenAPI spec version: 1
 * Contact: info@softwaredelcentro.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ar.com.sdc.sobio.model.v1;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Emotion
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-08-01T16:13:13.139-03:00")
public class Emotion {
  @JsonProperty("anger")
  private byte[] anger = null;

  @JsonProperty("disgust")
  private byte[] disgust = null;

  @JsonProperty("fear")
  private byte[] fear = null;

  @JsonProperty("happiness")
  private byte[] happiness = null;

  @JsonProperty("neutral")
  private byte[] neutral = null;

  @JsonProperty("sadness")
  private byte[] sadness = null;

  @JsonProperty("surprise")
  private byte[] surprise = null;

  public Emotion anger(byte[] anger) {
    this.anger = anger;
    return this;
  }

   /**
   * Get anger
   * @return anger
  **/
  @ApiModelProperty(value = "")
  public byte[] getAnger() {
    return anger;
  }

  public void setAnger(byte[] anger) {
    this.anger = anger;
  }

  public Emotion disgust(byte[] disgust) {
    this.disgust = disgust;
    return this;
  }

   /**
   * Get disgust
   * @return disgust
  **/
  @ApiModelProperty(value = "")
  public byte[] getDisgust() {
    return disgust;
  }

  public void setDisgust(byte[] disgust) {
    this.disgust = disgust;
  }

  public Emotion fear(byte[] fear) {
    this.fear = fear;
    return this;
  }

   /**
   * Get fear
   * @return fear
  **/
  @ApiModelProperty(value = "")
  public byte[] getFear() {
    return fear;
  }

  public void setFear(byte[] fear) {
    this.fear = fear;
  }

  public Emotion happiness(byte[] happiness) {
    this.happiness = happiness;
    return this;
  }

   /**
   * Get happiness
   * @return happiness
  **/
  @ApiModelProperty(value = "")
  public byte[] getHappiness() {
    return happiness;
  }

  public void setHappiness(byte[] happiness) {
    this.happiness = happiness;
  }

  public Emotion neutral(byte[] neutral) {
    this.neutral = neutral;
    return this;
  }

   /**
   * Get neutral
   * @return neutral
  **/
  @ApiModelProperty(value = "")
  public byte[] getNeutral() {
    return neutral;
  }

  public void setNeutral(byte[] neutral) {
    this.neutral = neutral;
  }

  public Emotion sadness(byte[] sadness) {
    this.sadness = sadness;
    return this;
  }

   /**
   * Get sadness
   * @return sadness
  **/
  @ApiModelProperty(value = "")
  public byte[] getSadness() {
    return sadness;
  }

  public void setSadness(byte[] sadness) {
    this.sadness = sadness;
  }

  public Emotion surprise(byte[] surprise) {
    this.surprise = surprise;
    return this;
  }

   /**
   * Get surprise
   * @return surprise
  **/
  @ApiModelProperty(value = "")
  public byte[] getSurprise() {
    return surprise;
  }

  public void setSurprise(byte[] surprise) {
    this.surprise = surprise;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Emotion emotion = (Emotion) o;
    return Objects.equals(this.anger, emotion.anger) &&
        Objects.equals(this.disgust, emotion.disgust) &&
        Objects.equals(this.fear, emotion.fear) &&
        Objects.equals(this.happiness, emotion.happiness) &&
        Objects.equals(this.neutral, emotion.neutral) &&
        Objects.equals(this.sadness, emotion.sadness) &&
        Objects.equals(this.surprise, emotion.surprise);
  }

  @Override
  public int hashCode() {
    return Objects.hash(anger, disgust, fear, happiness, neutral, sadness, surprise);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Emotion {\n");
    
    sb.append("    anger: ").append(toIndentedString(anger)).append("\n");
    sb.append("    disgust: ").append(toIndentedString(disgust)).append("\n");
    sb.append("    fear: ").append(toIndentedString(fear)).append("\n");
    sb.append("    happiness: ").append(toIndentedString(happiness)).append("\n");
    sb.append("    neutral: ").append(toIndentedString(neutral)).append("\n");
    sb.append("    sadness: ").append(toIndentedString(sadness)).append("\n");
    sb.append("    surprise: ").append(toIndentedString(surprise)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

