/*
 * SOBIO
 * SOBIO Biometric Services
 *
 * OpenAPI spec version: 1
 * Contact: info@softwaredelcentro.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ar.com.sdc.sobio.model.v1;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ExtractDNIARParameters
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-08-11T10:24:49.696-03:00")
public class ExtractDNIARParameters {
  @JsonProperty("extractAddress")
  private Boolean extractAddress = null;

  @JsonProperty("extractFace")
  private Boolean extractFace = null;

  @JsonProperty("extractMRZ")
  private Boolean extractMRZ = null;

  @JsonProperty("extractPDF417")
  private Boolean extractPDF417 = null;

  @JsonProperty("useCache")
  private Boolean useCache = null;

  public ExtractDNIARParameters extractAddress(Boolean extractAddress) {
    this.extractAddress = extractAddress;
    return this;
  }

   /**
   * Get extractAddress
   * @return extractAddress
  **/
  @ApiModelProperty(value = "")
  public Boolean isExtractAddress() {
    return extractAddress;
  }

  public void setExtractAddress(Boolean extractAddress) {
    this.extractAddress = extractAddress;
  }

  public ExtractDNIARParameters extractFace(Boolean extractFace) {
    this.extractFace = extractFace;
    return this;
  }

   /**
   * Get extractFace
   * @return extractFace
  **/
  @ApiModelProperty(value = "")
  public Boolean isExtractFace() {
    return extractFace;
  }

  public void setExtractFace(Boolean extractFace) {
    this.extractFace = extractFace;
  }

  public ExtractDNIARParameters extractMRZ(Boolean extractMRZ) {
    this.extractMRZ = extractMRZ;
    return this;
  }

   /**
   * Get extractMRZ
   * @return extractMRZ
  **/
  @ApiModelProperty(value = "")
  public Boolean isExtractMRZ() {
    return extractMRZ;
  }

  public void setExtractMRZ(Boolean extractMRZ) {
    this.extractMRZ = extractMRZ;
  }

  public ExtractDNIARParameters extractPDF417(Boolean extractPDF417) {
    this.extractPDF417 = extractPDF417;
    return this;
  }

   /**
   * Get extractPDF417
   * @return extractPDF417
  **/
  @ApiModelProperty(value = "")
  public Boolean isExtractPDF417() {
    return extractPDF417;
  }

  public void setExtractPDF417(Boolean extractPDF417) {
    this.extractPDF417 = extractPDF417;
  }

  public ExtractDNIARParameters useCache(Boolean useCache) {
    this.useCache = useCache;
    return this;
  }

   /**
   * Get useCache
   * @return useCache
  **/
  @ApiModelProperty(value = "")
  public Boolean isUseCache() {
    return useCache;
  }

  public void setUseCache(Boolean useCache) {
    this.useCache = useCache;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtractDNIARParameters extractDNIARParameters = (ExtractDNIARParameters) o;
    return Objects.equals(this.extractAddress, extractDNIARParameters.extractAddress) &&
        Objects.equals(this.extractFace, extractDNIARParameters.extractFace) &&
        Objects.equals(this.extractMRZ, extractDNIARParameters.extractMRZ) &&
        Objects.equals(this.extractPDF417, extractDNIARParameters.extractPDF417) &&
        Objects.equals(this.useCache, extractDNIARParameters.useCache);
  }

  @Override
  public int hashCode() {
    return Objects.hash(extractAddress, extractFace, extractMRZ, extractPDF417, useCache);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtractDNIARParameters {\n");
    
    sb.append("    extractAddress: ").append(toIndentedString(extractAddress)).append("\n");
    sb.append("    extractFace: ").append(toIndentedString(extractFace)).append("\n");
    sb.append("    extractMRZ: ").append(toIndentedString(extractMRZ)).append("\n");
    sb.append("    extractPDF417: ").append(toIndentedString(extractPDF417)).append("\n");
    sb.append("    useCache: ").append(toIndentedString(useCache)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

