/*
 * SOBIO
 * SOBIO Biometric Services
 *
 * OpenAPI spec version: 1
 * Contact: info@softwaredelcentro.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ar.com.sdc.sobio.model.v1;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ExtractDocumentInformationInput
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-12T14:38:20.209-03:00")
public class ExtractDocumentInformationInput {
  @JsonProperty("auditToken")
  private String auditToken = null;

  @JsonProperty("backImage")
  private byte[] backImage = null;

  @JsonProperty("frontImage")
  private byte[] frontImage = null;

  public ExtractDocumentInformationInput auditToken(String auditToken) {
    this.auditToken = auditToken;
    return this;
  }

   /**
   * Get auditToken
   * @return auditToken
  **/
  @ApiModelProperty(value = "")
  public String getAuditToken() {
    return auditToken;
  }

  public void setAuditToken(String auditToken) {
    this.auditToken = auditToken;
  }

  public ExtractDocumentInformationInput backImage(byte[] backImage) {
    this.backImage = backImage;
    return this;
  }

   /**
   * Get backImage
   * @return backImage
  **/
  @ApiModelProperty(value = "")
  public byte[] getBackImage() {
    return backImage;
  }

  public void setBackImage(byte[] backImage) {
    this.backImage = backImage;
  }

  public ExtractDocumentInformationInput frontImage(byte[] frontImage) {
    this.frontImage = frontImage;
    return this;
  }

   /**
   * Get frontImage
   * @return frontImage
  **/
  @ApiModelProperty(value = "")
  public byte[] getFrontImage() {
    return frontImage;
  }

  public void setFrontImage(byte[] frontImage) {
    this.frontImage = frontImage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtractDocumentInformationInput extractDocumentInformationInput = (ExtractDocumentInformationInput) o;
    return Objects.equals(this.auditToken, extractDocumentInformationInput.auditToken) &&
        Objects.equals(this.backImage, extractDocumentInformationInput.backImage) &&
        Objects.equals(this.frontImage, extractDocumentInformationInput.frontImage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(auditToken, backImage, frontImage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtractDocumentInformationInput {\n");
    
    sb.append("    auditToken: ").append(toIndentedString(auditToken)).append("\n");
    sb.append("    backImage: ").append(toIndentedString(backImage)).append("\n");
    sb.append("    frontImage: ").append(toIndentedString(frontImage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

