/*
 * SOBIO
 * SOBIO Biometric Services
 *
 * OpenAPI spec version: 1
 * Contact: info@softwaredelcentro.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ar.com.sdc.sobio.model.v1;

import java.util.Objects;
import ar.com.sdc.sobio.model.v1.FingerPrint;
import ar.com.sdc.sobio.model.v1.FingerPrintProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ExtractFingerPrintFromImageResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-26T11:28:18.014-03:00")
public class ExtractFingerPrintFromImageResult {
  @JsonProperty("auditId")
  private Long auditId = null;

  /**
   * Gets or Sets estado
   */
  public enum EstadoEnum {
    OK("OK"),
    
    LOW_QUALITY("LOW_QUALITY"),
    
    INVALID_IMAGE_RESOLUTION("INVALID_IMAGE_RESOLUTION");

    private String value;

    EstadoEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EstadoEnum fromValue(String text) {
      for (EstadoEnum b : EstadoEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("estado")
  private EstadoEnum estado = null;

  @JsonProperty("exception")
  private Boolean exception = null;

  @JsonProperty("huella")
  private FingerPrint huella = null;

  @JsonProperty("propiedadesHuella")
  private FingerPrintProperties propiedadesHuella = null;

  public ExtractFingerPrintFromImageResult auditId(Long auditId) {
    this.auditId = auditId;
    return this;
  }

   /**
   * Get auditId
   * @return auditId
  **/
  @ApiModelProperty(value = "")
  public Long getAuditId() {
    return auditId;
  }

  public void setAuditId(Long auditId) {
    this.auditId = auditId;
  }

  public ExtractFingerPrintFromImageResult estado(EstadoEnum estado) {
    this.estado = estado;
    return this;
  }

   /**
   * Get estado
   * @return estado
  **/
  @ApiModelProperty(value = "")
  public EstadoEnum getEstado() {
    return estado;
  }

  public void setEstado(EstadoEnum estado) {
    this.estado = estado;
  }

  public ExtractFingerPrintFromImageResult exception(Boolean exception) {
    this.exception = exception;
    return this;
  }

   /**
   * Get exception
   * @return exception
  **/
  @ApiModelProperty(value = "")
  public Boolean isException() {
    return exception;
  }

  public void setException(Boolean exception) {
    this.exception = exception;
  }

  public ExtractFingerPrintFromImageResult huella(FingerPrint huella) {
    this.huella = huella;
    return this;
  }

   /**
   * Get huella
   * @return huella
  **/
  @ApiModelProperty(value = "")
  public FingerPrint getHuella() {
    return huella;
  }

  public void setHuella(FingerPrint huella) {
    this.huella = huella;
  }

  public ExtractFingerPrintFromImageResult propiedadesHuella(FingerPrintProperties propiedadesHuella) {
    this.propiedadesHuella = propiedadesHuella;
    return this;
  }

   /**
   * Get propiedadesHuella
   * @return propiedadesHuella
  **/
  @ApiModelProperty(value = "")
  public FingerPrintProperties getPropiedadesHuella() {
    return propiedadesHuella;
  }

  public void setPropiedadesHuella(FingerPrintProperties propiedadesHuella) {
    this.propiedadesHuella = propiedadesHuella;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtractFingerPrintFromImageResult extractFingerPrintFromImageResult = (ExtractFingerPrintFromImageResult) o;
    return Objects.equals(this.auditId, extractFingerPrintFromImageResult.auditId) &&
        Objects.equals(this.estado, extractFingerPrintFromImageResult.estado) &&
        Objects.equals(this.exception, extractFingerPrintFromImageResult.exception) &&
        Objects.equals(this.huella, extractFingerPrintFromImageResult.huella) &&
        Objects.equals(this.propiedadesHuella, extractFingerPrintFromImageResult.propiedadesHuella);
  }

  @Override
  public int hashCode() {
    return Objects.hash(auditId, estado, exception, huella, propiedadesHuella);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtractFingerPrintFromImageResult {\n");
    
    sb.append("    auditId: ").append(toIndentedString(auditId)).append("\n");
    sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
    sb.append("    exception: ").append(toIndentedString(exception)).append("\n");
    sb.append("    huella: ").append(toIndentedString(huella)).append("\n");
    sb.append("    propiedadesHuella: ").append(toIndentedString(propiedadesHuella)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

