/*
 * SOBIO
 * SOBIO Biometric Services
 *
 * OpenAPI spec version: 1
 * Contact: info@softwaredelcentro.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ar.com.sdc.sobio.model.v1;

import java.util.Objects;
import ar.com.sdc.sobio.model.v1.TextIndependentVoiceExtractionParameters;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ExtractTextIndependentVoiceFromAudioInput
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-02T11:05:26.582-03:00")
public class ExtractTextIndependentVoiceFromAudioInput {
  @JsonProperty("audio")
  private byte[] audio = null;

  @JsonProperty("auditToken")
  private String auditToken = null;

  @JsonProperty("params")
  private TextIndependentVoiceExtractionParameters params = null;

  public ExtractTextIndependentVoiceFromAudioInput audio(byte[] audio) {
    this.audio = audio;
    return this;
  }

   /**
   * Get audio
   * @return audio
  **/
  @ApiModelProperty(required = true, value = "")
  public byte[] getAudio() {
    return audio;
  }

  public void setAudio(byte[] audio) {
    this.audio = audio;
  }

  public ExtractTextIndependentVoiceFromAudioInput auditToken(String auditToken) {
    this.auditToken = auditToken;
    return this;
  }

   /**
   * Get auditToken
   * @return auditToken
  **/
  @ApiModelProperty(required = true, value = "")
  public String getAuditToken() {
    return auditToken;
  }

  public void setAuditToken(String auditToken) {
    this.auditToken = auditToken;
  }

  public ExtractTextIndependentVoiceFromAudioInput params(TextIndependentVoiceExtractionParameters params) {
    this.params = params;
    return this;
  }

   /**
   * Get params
   * @return params
  **/
  @ApiModelProperty(value = "")
  public TextIndependentVoiceExtractionParameters getParams() {
    return params;
  }

  public void setParams(TextIndependentVoiceExtractionParameters params) {
    this.params = params;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtractTextIndependentVoiceFromAudioInput extractTextIndependentVoiceFromAudioInput = (ExtractTextIndependentVoiceFromAudioInput) o;
    return Objects.equals(this.audio, extractTextIndependentVoiceFromAudioInput.audio) &&
        Objects.equals(this.auditToken, extractTextIndependentVoiceFromAudioInput.auditToken) &&
        Objects.equals(this.params, extractTextIndependentVoiceFromAudioInput.params);
  }

  @Override
  public int hashCode() {
    return Objects.hash(audio, auditToken, params);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtractTextIndependentVoiceFromAudioInput {\n");
    
    sb.append("    audio: ").append(toIndentedString(audio)).append("\n");
    sb.append("    auditToken: ").append(toIndentedString(auditToken)).append("\n");
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

