/*
 * BIOMIX
 * BIOMIX Biometric Services
 *
 * OpenAPI spec version: 1
 * Contact: soporte@securbase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ar.com.sdc.sobio.model.v1;

import java.util.Objects;
import ar.com.sdc.sobio.model.v1.MrzDate;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * MrzRecord
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-07-22T14:48:09.641-03:00")
public class MrzRecord {
  /**
   * Gets or Sets code
   */
  public enum CodeEnum {
    PASSPORT("Passport"),
    
    TYPEI("TypeI"),
    
    TYPEA("TypeA"),
    
    CREWMEMBER("CrewMember"),
    
    TYPEC("TypeC"),
    
    TYPEV("TypeV"),
    
    MIGRANT("Migrant");

    private String value;

    CodeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CodeEnum fromValue(String text) {
      for (CodeEnum b : CodeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("code")
  private CodeEnum code = null;

  @JsonProperty("code1")
  private String code1 = null;

  @JsonProperty("code2")
  private String code2 = null;

  @JsonProperty("dateOfBirth")
  private MrzDate dateOfBirth = null;

  @JsonProperty("documentNumber")
  private String documentNumber = null;

  @JsonProperty("expirationDate")
  private MrzDate expirationDate = null;

  /**
   * Gets or Sets format
   */
  public enum FormatEnum {
    MRTD_TD1("MRTD_TD1"),
    
    FRENCH_ID("FRENCH_ID"),
    
    MRV_VISA_B("MRV_VISA_B"),
    
    MRTD_TD2("MRTD_TD2"),
    
    MRV_VISA_A("MRV_VISA_A"),
    
    PASSPORT("PASSPORT"),
    
    SLOVAK_ID_234("SLOVAK_ID_234");

    private String value;

    FormatEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FormatEnum fromValue(String text) {
      for (FormatEnum b : FormatEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("format")
  private FormatEnum format = null;

  @JsonProperty("givenNames")
  private String givenNames = null;

  @JsonProperty("issuingCountry")
  private String issuingCountry = null;

  @JsonProperty("nationality")
  private String nationality = null;

  /**
   * Gets or Sets sex
   */
  public enum SexEnum {
    MALE("Male"),
    
    FEMALE("Female"),
    
    UNSPECIFIED("Unspecified");

    private String value;

    SexEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SexEnum fromValue(String text) {
      for (SexEnum b : SexEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("sex")
  private SexEnum sex = null;

  @JsonProperty("surname")
  private String surname = null;

  @JsonProperty("validComposite")
  private Boolean validComposite = null;

  @JsonProperty("validDateOfBirth")
  private Boolean validDateOfBirth = null;

  @JsonProperty("validDocumentNumber")
  private Boolean validDocumentNumber = null;

  @JsonProperty("validExpirationDate")
  private Boolean validExpirationDate = null;

  public MrzRecord code(CodeEnum code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(value = "")
  public CodeEnum getCode() {
    return code;
  }

  public void setCode(CodeEnum code) {
    this.code = code;
  }

  public MrzRecord code1(String code1) {
    this.code1 = code1;
    return this;
  }

   /**
   * Get code1
   * @return code1
  **/
  @ApiModelProperty(value = "")
  public String getCode1() {
    return code1;
  }

  public void setCode1(String code1) {
    this.code1 = code1;
  }

  public MrzRecord code2(String code2) {
    this.code2 = code2;
    return this;
  }

   /**
   * Get code2
   * @return code2
  **/
  @ApiModelProperty(value = "")
  public String getCode2() {
    return code2;
  }

  public void setCode2(String code2) {
    this.code2 = code2;
  }

  public MrzRecord dateOfBirth(MrzDate dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
    return this;
  }

   /**
   * Get dateOfBirth
   * @return dateOfBirth
  **/
  @ApiModelProperty(value = "")
  public MrzDate getDateOfBirth() {
    return dateOfBirth;
  }

  public void setDateOfBirth(MrzDate dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
  }

  public MrzRecord documentNumber(String documentNumber) {
    this.documentNumber = documentNumber;
    return this;
  }

   /**
   * Get documentNumber
   * @return documentNumber
  **/
  @ApiModelProperty(value = "")
  public String getDocumentNumber() {
    return documentNumber;
  }

  public void setDocumentNumber(String documentNumber) {
    this.documentNumber = documentNumber;
  }

  public MrzRecord expirationDate(MrzDate expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Get expirationDate
   * @return expirationDate
  **/
  @ApiModelProperty(value = "")
  public MrzDate getExpirationDate() {
    return expirationDate;
  }

  public void setExpirationDate(MrzDate expirationDate) {
    this.expirationDate = expirationDate;
  }

  public MrzRecord format(FormatEnum format) {
    this.format = format;
    return this;
  }

   /**
   * Get format
   * @return format
  **/
  @ApiModelProperty(value = "")
  public FormatEnum getFormat() {
    return format;
  }

  public void setFormat(FormatEnum format) {
    this.format = format;
  }

  public MrzRecord givenNames(String givenNames) {
    this.givenNames = givenNames;
    return this;
  }

   /**
   * Get givenNames
   * @return givenNames
  **/
  @ApiModelProperty(value = "")
  public String getGivenNames() {
    return givenNames;
  }

  public void setGivenNames(String givenNames) {
    this.givenNames = givenNames;
  }

  public MrzRecord issuingCountry(String issuingCountry) {
    this.issuingCountry = issuingCountry;
    return this;
  }

   /**
   * Get issuingCountry
   * @return issuingCountry
  **/
  @ApiModelProperty(value = "")
  public String getIssuingCountry() {
    return issuingCountry;
  }

  public void setIssuingCountry(String issuingCountry) {
    this.issuingCountry = issuingCountry;
  }

  public MrzRecord nationality(String nationality) {
    this.nationality = nationality;
    return this;
  }

   /**
   * Get nationality
   * @return nationality
  **/
  @ApiModelProperty(value = "")
  public String getNationality() {
    return nationality;
  }

  public void setNationality(String nationality) {
    this.nationality = nationality;
  }

  public MrzRecord sex(SexEnum sex) {
    this.sex = sex;
    return this;
  }

   /**
   * Get sex
   * @return sex
  **/
  @ApiModelProperty(value = "")
  public SexEnum getSex() {
    return sex;
  }

  public void setSex(SexEnum sex) {
    this.sex = sex;
  }

  public MrzRecord surname(String surname) {
    this.surname = surname;
    return this;
  }

   /**
   * Get surname
   * @return surname
  **/
  @ApiModelProperty(value = "")
  public String getSurname() {
    return surname;
  }

  public void setSurname(String surname) {
    this.surname = surname;
  }

  public MrzRecord validComposite(Boolean validComposite) {
    this.validComposite = validComposite;
    return this;
  }

   /**
   * Get validComposite
   * @return validComposite
  **/
  @ApiModelProperty(value = "")
  public Boolean isValidComposite() {
    return validComposite;
  }

  public void setValidComposite(Boolean validComposite) {
    this.validComposite = validComposite;
  }

  public MrzRecord validDateOfBirth(Boolean validDateOfBirth) {
    this.validDateOfBirth = validDateOfBirth;
    return this;
  }

   /**
   * Get validDateOfBirth
   * @return validDateOfBirth
  **/
  @ApiModelProperty(value = "")
  public Boolean isValidDateOfBirth() {
    return validDateOfBirth;
  }

  public void setValidDateOfBirth(Boolean validDateOfBirth) {
    this.validDateOfBirth = validDateOfBirth;
  }

  public MrzRecord validDocumentNumber(Boolean validDocumentNumber) {
    this.validDocumentNumber = validDocumentNumber;
    return this;
  }

   /**
   * Get validDocumentNumber
   * @return validDocumentNumber
  **/
  @ApiModelProperty(value = "")
  public Boolean isValidDocumentNumber() {
    return validDocumentNumber;
  }

  public void setValidDocumentNumber(Boolean validDocumentNumber) {
    this.validDocumentNumber = validDocumentNumber;
  }

  public MrzRecord validExpirationDate(Boolean validExpirationDate) {
    this.validExpirationDate = validExpirationDate;
    return this;
  }

   /**
   * Get validExpirationDate
   * @return validExpirationDate
  **/
  @ApiModelProperty(value = "")
  public Boolean isValidExpirationDate() {
    return validExpirationDate;
  }

  public void setValidExpirationDate(Boolean validExpirationDate) {
    this.validExpirationDate = validExpirationDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MrzRecord mrzRecord = (MrzRecord) o;
    return Objects.equals(this.code, mrzRecord.code) &&
        Objects.equals(this.code1, mrzRecord.code1) &&
        Objects.equals(this.code2, mrzRecord.code2) &&
        Objects.equals(this.dateOfBirth, mrzRecord.dateOfBirth) &&
        Objects.equals(this.documentNumber, mrzRecord.documentNumber) &&
        Objects.equals(this.expirationDate, mrzRecord.expirationDate) &&
        Objects.equals(this.format, mrzRecord.format) &&
        Objects.equals(this.givenNames, mrzRecord.givenNames) &&
        Objects.equals(this.issuingCountry, mrzRecord.issuingCountry) &&
        Objects.equals(this.nationality, mrzRecord.nationality) &&
        Objects.equals(this.sex, mrzRecord.sex) &&
        Objects.equals(this.surname, mrzRecord.surname) &&
        Objects.equals(this.validComposite, mrzRecord.validComposite) &&
        Objects.equals(this.validDateOfBirth, mrzRecord.validDateOfBirth) &&
        Objects.equals(this.validDocumentNumber, mrzRecord.validDocumentNumber) &&
        Objects.equals(this.validExpirationDate, mrzRecord.validExpirationDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, code1, code2, dateOfBirth, documentNumber, expirationDate, format, givenNames, issuingCountry, nationality, sex, surname, validComposite, validDateOfBirth, validDocumentNumber, validExpirationDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MrzRecord {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    code1: ").append(toIndentedString(code1)).append("\n");
    sb.append("    code2: ").append(toIndentedString(code2)).append("\n");
    sb.append("    dateOfBirth: ").append(toIndentedString(dateOfBirth)).append("\n");
    sb.append("    documentNumber: ").append(toIndentedString(documentNumber)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    givenNames: ").append(toIndentedString(givenNames)).append("\n");
    sb.append("    issuingCountry: ").append(toIndentedString(issuingCountry)).append("\n");
    sb.append("    nationality: ").append(toIndentedString(nationality)).append("\n");
    sb.append("    sex: ").append(toIndentedString(sex)).append("\n");
    sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
    sb.append("    validComposite: ").append(toIndentedString(validComposite)).append("\n");
    sb.append("    validDateOfBirth: ").append(toIndentedString(validDateOfBirth)).append("\n");
    sb.append("    validDocumentNumber: ").append(toIndentedString(validDocumentNumber)).append("\n");
    sb.append("    validExpirationDate: ").append(toIndentedString(validExpirationDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

