/*
 * SOBIO
 * SOBIO Biometric Services
 *
 * OpenAPI spec version: 1
 * Contact: info@softwaredelcentro.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ar.com.sdc.sobio.model.v1;

import java.util.Objects;
import ar.com.sdc.sobio.model.v1.Point;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Position
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-06T15:59:21.589-03:00")
public class Position {
  @JsonProperty("height")
  private Integer height = null;

  @JsonProperty("pitch")
  private Float pitch = null;

  @JsonProperty("points")
  private List<Point> points = null;

  @JsonProperty("roll")
  private Float roll = null;

  @JsonProperty("width")
  private Integer width = null;

  @JsonProperty("x")
  private Integer x = null;

  @JsonProperty("y")
  private Integer y = null;

  @JsonProperty("yaw")
  private Float yaw = null;

  public Position height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @ApiModelProperty(value = "")
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }

  public Position pitch(Float pitch) {
    this.pitch = pitch;
    return this;
  }

   /**
   * Get pitch
   * @return pitch
  **/
  @ApiModelProperty(value = "")
  public Float getPitch() {
    return pitch;
  }

  public void setPitch(Float pitch) {
    this.pitch = pitch;
  }

  public Position points(List<Point> points) {
    this.points = points;
    return this;
  }

  public Position addPointsItem(Point pointsItem) {
    if (this.points == null) {
      this.points = new ArrayList<Point>();
    }
    this.points.add(pointsItem);
    return this;
  }

   /**
   * Get points
   * @return points
  **/
  @ApiModelProperty(value = "")
  public List<Point> getPoints() {
    return points;
  }

  public void setPoints(List<Point> points) {
    this.points = points;
  }

  public Position roll(Float roll) {
    this.roll = roll;
    return this;
  }

   /**
   * Get roll
   * @return roll
  **/
  @ApiModelProperty(value = "")
  public Float getRoll() {
    return roll;
  }

  public void setRoll(Float roll) {
    this.roll = roll;
  }

  public Position width(Integer width) {
    this.width = width;
    return this;
  }

   /**
   * Get width
   * @return width
  **/
  @ApiModelProperty(value = "")
  public Integer getWidth() {
    return width;
  }

  public void setWidth(Integer width) {
    this.width = width;
  }

  public Position x(Integer x) {
    this.x = x;
    return this;
  }

   /**
   * Get x
   * @return x
  **/
  @ApiModelProperty(value = "")
  public Integer getX() {
    return x;
  }

  public void setX(Integer x) {
    this.x = x;
  }

  public Position y(Integer y) {
    this.y = y;
    return this;
  }

   /**
   * Get y
   * @return y
  **/
  @ApiModelProperty(value = "")
  public Integer getY() {
    return y;
  }

  public void setY(Integer y) {
    this.y = y;
  }

  public Position yaw(Float yaw) {
    this.yaw = yaw;
    return this;
  }

   /**
   * Get yaw
   * @return yaw
  **/
  @ApiModelProperty(value = "")
  public Float getYaw() {
    return yaw;
  }

  public void setYaw(Float yaw) {
    this.yaw = yaw;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Position position = (Position) o;
    return Objects.equals(this.height, position.height) &&
        Objects.equals(this.pitch, position.pitch) &&
        Objects.equals(this.points, position.points) &&
        Objects.equals(this.roll, position.roll) &&
        Objects.equals(this.width, position.width) &&
        Objects.equals(this.x, position.x) &&
        Objects.equals(this.y, position.y) &&
        Objects.equals(this.yaw, position.yaw);
  }

  @Override
  public int hashCode() {
    return Objects.hash(height, pitch, points, roll, width, x, y, yaw);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Position {\n");
    
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    pitch: ").append(toIndentedString(pitch)).append("\n");
    sb.append("    points: ").append(toIndentedString(points)).append("\n");
    sb.append("    roll: ").append(toIndentedString(roll)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("    yaw: ").append(toIndentedString(yaw)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

