/*
 * SOBIO
 * SOBIO Biometric Services
 *
 * OpenAPI spec version: 1
 * Contact: info@softwaredelcentro.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ar.com.sdc.sobio.model.v1;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * UITemplateMetada
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-11T17:07:14.771-03:00")
public class UITemplateMetada {
  @JsonProperty("fechaCreacionTemplate")
  private DateTime fechaCreacionTemplate = null;

  public UITemplateMetada fechaCreacionTemplate(DateTime fechaCreacionTemplate) {
    this.fechaCreacionTemplate = fechaCreacionTemplate;
    return this;
  }

   /**
   * Get fechaCreacionTemplate
   * @return fechaCreacionTemplate
  **/
  @ApiModelProperty(value = "")
  public DateTime getFechaCreacionTemplate() {
    return fechaCreacionTemplate;
  }

  public void setFechaCreacionTemplate(DateTime fechaCreacionTemplate) {
    this.fechaCreacionTemplate = fechaCreacionTemplate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UITemplateMetada uiTemplateMetada = (UITemplateMetada) o;
    return Objects.equals(this.fechaCreacionTemplate, uiTemplateMetada.fechaCreacionTemplate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fechaCreacionTemplate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UITemplateMetada {\n");
    
    sb.append("    fechaCreacionTemplate: ").append(toIndentedString(fechaCreacionTemplate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

