/*
 * BIOMIX
 * BIOMIX Biometric Services
 *
 * OpenAPI spec version: 1
 * Contact: soporte@securbase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ar.com.sdc.sobio.model.v1;

import java.util.Objects;
import ar.com.sdc.sobio.model.v1.BiometricData;
import ar.com.sdc.sobio.model.v1.VerificationParameters;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * UIVerifyT2TInput
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-07-22T14:48:09.641-03:00")
public class UIVerifyT2TInput {
  @JsonProperty("auditToken")
  private String auditToken = null;

  @JsonProperty("bioInfo")
  private BiometricData bioInfo = null;

  @JsonProperty("params")
  private VerificationParameters params = null;

  @JsonProperty("uiTemplate")
  private String uiTemplate = null;

  @JsonProperty("uiTemplate2")
  private String uiTemplate2 = null;

  public UIVerifyT2TInput auditToken(String auditToken) {
    this.auditToken = auditToken;
    return this;
  }

   /**
   * Get auditToken
   * @return auditToken
  **/
  @ApiModelProperty(required = true, value = "")
  public String getAuditToken() {
    return auditToken;
  }

  public void setAuditToken(String auditToken) {
    this.auditToken = auditToken;
  }

  public UIVerifyT2TInput bioInfo(BiometricData bioInfo) {
    this.bioInfo = bioInfo;
    return this;
  }

   /**
   * Get bioInfo
   * @return bioInfo
  **/
  @ApiModelProperty(value = "")
  public BiometricData getBioInfo() {
    return bioInfo;
  }

  public void setBioInfo(BiometricData bioInfo) {
    this.bioInfo = bioInfo;
  }

  public UIVerifyT2TInput params(VerificationParameters params) {
    this.params = params;
    return this;
  }

   /**
   * Get params
   * @return params
  **/
  @ApiModelProperty(value = "")
  public VerificationParameters getParams() {
    return params;
  }

  public void setParams(VerificationParameters params) {
    this.params = params;
  }

  public UIVerifyT2TInput uiTemplate(String uiTemplate) {
    this.uiTemplate = uiTemplate;
    return this;
  }

   /**
   * Get uiTemplate
   * @return uiTemplate
  **/
  @ApiModelProperty(required = true, value = "")
  public String getUiTemplate() {
    return uiTemplate;
  }

  public void setUiTemplate(String uiTemplate) {
    this.uiTemplate = uiTemplate;
  }

  public UIVerifyT2TInput uiTemplate2(String uiTemplate2) {
    this.uiTemplate2 = uiTemplate2;
    return this;
  }

   /**
   * Get uiTemplate2
   * @return uiTemplate2
  **/
  @ApiModelProperty(value = "")
  public String getUiTemplate2() {
    return uiTemplate2;
  }

  public void setUiTemplate2(String uiTemplate2) {
    this.uiTemplate2 = uiTemplate2;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UIVerifyT2TInput uiVerifyT2TInput = (UIVerifyT2TInput) o;
    return Objects.equals(this.auditToken, uiVerifyT2TInput.auditToken) &&
        Objects.equals(this.bioInfo, uiVerifyT2TInput.bioInfo) &&
        Objects.equals(this.params, uiVerifyT2TInput.params) &&
        Objects.equals(this.uiTemplate, uiVerifyT2TInput.uiTemplate) &&
        Objects.equals(this.uiTemplate2, uiVerifyT2TInput.uiTemplate2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(auditToken, bioInfo, params, uiTemplate, uiTemplate2);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UIVerifyT2TInput {\n");
    
    sb.append("    auditToken: ").append(toIndentedString(auditToken)).append("\n");
    sb.append("    bioInfo: ").append(toIndentedString(bioInfo)).append("\n");
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("    uiTemplate: ").append(toIndentedString(uiTemplate)).append("\n");
    sb.append("    uiTemplate2: ").append(toIndentedString(uiTemplate2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

