/*
 * BIOMIX
 * BIOMIX Biometric Services
 *
 * OpenAPI spec version: 1
 * Contact: soporte@securbase.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ar.com.sdc.sobio.model.v1;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * UIVerifyFASParameters
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-07-22T14:48:09.641-03:00")
public class UIVerifyFASParameters {
  @JsonProperty("extractFace")
  private Boolean extractFace = null;

  @JsonProperty("threshold")
  private Double threshold = null;

  public UIVerifyFASParameters extractFace(Boolean extractFace) {
    this.extractFace = extractFace;
    return this;
  }

   /**
   * Get extractFace
   * @return extractFace
  **/
  @ApiModelProperty(value = "")
  public Boolean isExtractFace() {
    return extractFace;
  }

  public void setExtractFace(Boolean extractFace) {
    this.extractFace = extractFace;
  }

  public UIVerifyFASParameters threshold(Double threshold) {
    this.threshold = threshold;
    return this;
  }

   /**
   * Get threshold
   * @return threshold
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getThreshold() {
    return threshold;
  }

  public void setThreshold(Double threshold) {
    this.threshold = threshold;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UIVerifyFASParameters uiVerifyFASParameters = (UIVerifyFASParameters) o;
    return Objects.equals(this.extractFace, uiVerifyFASParameters.extractFace) &&
        Objects.equals(this.threshold, uiVerifyFASParameters.threshold);
  }

  @Override
  public int hashCode() {
    return Objects.hash(extractFace, threshold);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UIVerifyFASParameters {\n");
    
    sb.append("    extractFace: ").append(toIndentedString(extractFace)).append("\n");
    sb.append("    threshold: ").append(toIndentedString(threshold)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

