/*
 * SOBIO
 * SOBIO Biometric Services
 *
 * OpenAPI spec version: 1
 * Contact: info@softwaredelcentro.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ar.com.sdc.sobio.model.v1;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Voice
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-26T12:55:02.459-03:00")
public class Voice {
  @JsonProperty("audio")
  private byte[] audio = null;

  @JsonProperty("calidad")
  private Integer calidad = null;

  @JsonProperty("frase")
  private Integer frase = null;

  @JsonProperty("snr")
  private Integer snr = null;

  @JsonProperty("template")
  private byte[] template = null;

  @JsonProperty("volumen")
  private Double volumen = null;

  public Voice audio(byte[] audio) {
    this.audio = audio;
    return this;
  }

   /**
   * Get audio
   * @return audio
  **/
  @ApiModelProperty(value = "")
  public byte[] getAudio() {
    return audio;
  }

  public void setAudio(byte[] audio) {
    this.audio = audio;
  }

  public Voice calidad(Integer calidad) {
    this.calidad = calidad;
    return this;
  }

   /**
   * Get calidad
   * @return calidad
  **/
  @ApiModelProperty(value = "")
  public Integer getCalidad() {
    return calidad;
  }

  public void setCalidad(Integer calidad) {
    this.calidad = calidad;
  }

  public Voice frase(Integer frase) {
    this.frase = frase;
    return this;
  }

   /**
   * Get frase
   * @return frase
  **/
  @ApiModelProperty(value = "")
  public Integer getFrase() {
    return frase;
  }

  public void setFrase(Integer frase) {
    this.frase = frase;
  }

  public Voice snr(Integer snr) {
    this.snr = snr;
    return this;
  }

   /**
   * Get snr
   * @return snr
  **/
  @ApiModelProperty(value = "")
  public Integer getSnr() {
    return snr;
  }

  public void setSnr(Integer snr) {
    this.snr = snr;
  }

  public Voice template(byte[] template) {
    this.template = template;
    return this;
  }

   /**
   * Get template
   * @return template
  **/
  @ApiModelProperty(value = "")
  public byte[] getTemplate() {
    return template;
  }

  public void setTemplate(byte[] template) {
    this.template = template;
  }

  public Voice volumen(Double volumen) {
    this.volumen = volumen;
    return this;
  }

   /**
   * Get volumen
   * @return volumen
  **/
  @ApiModelProperty(value = "")
  public Double getVolumen() {
    return volumen;
  }

  public void setVolumen(Double volumen) {
    this.volumen = volumen;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Voice voice = (Voice) o;
    return Objects.equals(this.audio, voice.audio) &&
        Objects.equals(this.calidad, voice.calidad) &&
        Objects.equals(this.frase, voice.frase) &&
        Objects.equals(this.snr, voice.snr) &&
        Objects.equals(this.template, voice.template) &&
        Objects.equals(this.volumen, voice.volumen);
  }

  @Override
  public int hashCode() {
    return Objects.hash(audio, calidad, frase, snr, template, volumen);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Voice {\n");
    
    sb.append("    audio: ").append(toIndentedString(audio)).append("\n");
    sb.append("    calidad: ").append(toIndentedString(calidad)).append("\n");
    sb.append("    frase: ").append(toIndentedString(frase)).append("\n");
    sb.append("    snr: ").append(toIndentedString(snr)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    volumen: ").append(toIndentedString(volumen)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

