/*
 * SOBIO
 * SOBIO Biometric Services
 *
 * OpenAPI spec version: 1
 * Contact: info@softwaredelcentro.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ar.com.sdc.sobio.api.v1;

import static org.junit.Assert.assertEquals;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;

import org.apache.commons.io.IOUtils;
import org.junit.Test;

import ar.com.sdc.sobio.client.v1.ApiException;
import ar.com.sdc.sobio.model.v1.ExtractFaceFromImageInput;
import ar.com.sdc.sobio.model.v1.ExtractFaceFromImageResult;
import ar.com.sdc.sobio.model.v1.FaceExtractionParams;
import ar.com.sdc.sobio.model.v1.Gender;

public class SOBIOClienteApiV1Test {

	protected byte[] cargar(String rscName) throws IOException {
		ClassLoader classLoader = getClass().getClassLoader();
		File file = new File(classLoader.getResource(rscName).getFile());
		FileInputStream fis = new FileInputStream(file);
		byte[] cnt = IOUtils.toByteArray(fis);
		fis.close();
		return cnt;
	}

	@Test
	public void extractFace01Test() throws ApiException, IOException {
		ExtractionApi api = new ExtractionApi();
		ExtractFaceFromImageInput input = new ExtractFaceFromImageInput();
		input.setAuditToken("tok123");
		input.setImage(cargar("paul-1.jpg"));
		FaceExtractionParams params = new FaceExtractionParams();
		params.detectAge(true);
		params.setDetectGender(true);
		input.setParams(params);
		ExtractFaceFromImageResult output = api.extractFaceImage(input);
		assertEquals(output.getExtractedFaces().size(), 1);
		assertEquals(output.getExtractedFaces().get(0).getProperties().getGender().getType(), Gender.TypeEnum.MALE);

	}
}
